### ISSUE TITLE
Fields are not ordered consistently

### ISSUE THREAD

**Issue by dhrosa** [dhrosa/udataclasses#13]
```python
from udataclasses import dataclass, field

@dataclass
class Product:
    name: str = field()
    quantity: int = 0
```

Output:
```
Traceback (most recent call last):
  File "smoke_test.py", line 6, in <module>
  File "/code/udataclasses/decorator.py", line 28, in dataclass
  File "/code/udataclasses/decorator.py", line 21, in wrapper
  File "/code/udataclasses/decorator.py", line 51, in _dataclass
  File "/code/udataclasses/decorator.py", line 85, in make_methods
  File "/code/udataclasses/decorator.py", line 77, in add_method
  File "<string>", line 1, in <module>
SyntaxError: non-default argument follows default argument
```

**Comment by dhrosa** [comment]
This failure is actually specific to MicroPython and doesn't reproduce in CPython.

Python dicts became insertion-ordered in Python 3.6. MicroPython implements something resembling Python 3.4, so dicts are in an arbitrary order.

This means we don't have a way to preserve the source field ordering.

As a workaround, we can sort the fields alphabetically to produce a consistent ordering. We might also want to provide a way for the user to explicitly control the order (e.g. a new parameter to `field()` to specify its ordering index)
